### ISSUE TITLE
`methodNotSupported` instead of `invalidDid` error if method is not key

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-key-test-suite#24]
One of the tests is currently:

> MUST raise invalidDid error if method is not key

Per the discussion we recently had in DID Resolution (https://github.com/w3c-ccg/did-resolution/pull/74 and https://github.com/w3c-ccg/did-resolution/issues/72), I believe that error should be `methodNotSupported` instead of `invalidDid`.

**Comment by aljones15** [comment]
[closing as](https://github.com/w3c-ccg/did-key-test-suite/pull/27)
